### ISSUE TITLE
[Lableing]: FloDisMod Digital Infrastructure

### ISSUE THREAD

**Issue by helpfultangent** [FloDisMod/flodismod.github.io#2]
## Summary 
Suggest adjusting language describing the data services to call them "digital infrastructure"

## Proposed solution
Modify the navigation title currently "data repository" to digital infrastructure

## Other considerations
By adjusting the description, we can describe the larger set of digital services that FloDisMod is leveraging and this will help with long-term sustainability for the project. It also will help the team expand over time. 

## Additional context
We are using: 
TDR
PT2050
DesignSafe
and other services. 

In addition, we are developing new capabilities.  Starting with language around FAIR approaches and emphasizing the reusability/scalability will set the project up for future support and collaborations

**Comment by largeseabass** [comment]
Thank you for the suggestion. This has been updated in the newest version.
